## **1. Numpy**

* 수학, 과학 계산용  패키지
* 성능 : 파이썬의 리스트보다 빠름
* 메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용
* 빌트인 함수 : 선형대수, 통계 관련 여러 함수들을 내장

In [1]:
# !pip install numpy

In [5]:
import numpy

In [6]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [7]:
# 별칭(alias) 지정
import numpy as np

In [8]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### **1-1. array(배열)**
* 여러 값들의 그룹

In [9]:
arr = np.array([1, 2, 3, 4])

In [10]:
arr

array([1, 2, 3, 4])

In [12]:
type(arr) # numpy.ndarray = n dimension array

numpy.ndarray

In [14]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [15]:
# 리스트를 ndarray로 생성하는 방법
arr1 = np.array(list1)
arr2 = np.array(list2)

In [17]:
print(arr1)
print(type(arr1))
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [18]:
arr1.shape # 차원

(4,)

In [19]:
arr2.shape

(2, 4)

### **1-2. array의 data 타입**
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [20]:
list = [1, 3.14, 'python', '🎃', '1234', 'True']

In [21]:
list

[1, 3.14, 'python', '🎃', '1234', 'True']

In [23]:
arr = np.array([1, 2, 3, 4])

In [24]:
arr

array([1, 2, 3, 4])

In [29]:
arr = np.array([1, 2, 3, 3.14, 5]) # 더 큰 자료형에 맞추어 데이터 타입이 맞춰짐 (정수 < 소수)

In [30]:
arr

array([1.  , 2.  , 3.  , 3.14, 5.  ])

In [31]:
arr = np.array([1, 2, 3, 3.14, '🎃', '1234']) # (정수 < 소수 < 문자열)

In [32]:
arr

array(['1', '2', '3', '3.14', '🎃', '1234'], dtype='<U32')

In [33]:
# int와 float 타입이 같이 존재하는 경우 int로 설정하는 방법
arr = np.array([1, 2, 3, 3.14, 5], dtype = int)

In [34]:
arr

array([1, 2, 3, 3, 5])

In [39]:
# int와 str 타입이 같이 존재하는 경우 int로 설정하는 방법(단, int로 바꿀 수 있는 문자인 경우)

In [40]:
arr = np.array([1, 2, 3, 3.14, '1234'], dtype = int)

In [41]:
arr

array([   1,    2,    3,    3, 1234])

### **1-3. 슬라이싱**
* 배열의 부분 선택

In [42]:
arr = np.array(['🎃','❤','🎀','🎁','🎄'])
arr.shape

(5,)

In [43]:
print(arr[0])
print(arr[4])
print(arr[-1])

🎃
🎄
🎄


In [45]:
print(arr[0:3])
print(arr[2:])
print(arr[:2])

['🎃' '❤' '🎀']
['🎀' '🎁' '🎄']
['🎃' '❤']


In [48]:
arr2d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [49]:
arr2d.shape

(3, 4)

In [50]:
arr2d[0, 2]

3

In [51]:
arr2d[2, 1]

10

In [52]:
# 0행을 모두 가져오기
print(arr2d[0])
print(arr2d[0,])
print(arr2d[0,:])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [53]:
# 1열을 모두 가져오기
print(arr2d[:,1])

[ 2  6 10]


In [54]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

### **1-4. Fancy 인덱싱**
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [56]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [57]:
idx = [1, 3, 5]

In [58]:
arr[idx]

array([23,  7, 65])

In [59]:
arr2d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [61]:
arr2d[[0, 2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### **1-5. Boolean 인덱싱**
* 조건 필터링을 통한 Boolean 값을 이용한 색인

In [62]:
arr = np.array(['🎃','❤','🎀','🎁','🎄'])

In [63]:
myValue = [True, False, True, False, True]

In [64]:
arr[myValue]

array(['🎃', '🎀', '🎄'], dtype='<U1')

In [65]:
# myValue = [True, False, True, False]
# 개수가 맞지 않으면 IndexError 뜸

In [66]:
arr2d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [67]:
arr2d > 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
arr2d < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [69]:
arr2d[arr2d>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
arr2d[arr2d<7]

array([1, 2, 3, 4, 5, 6])

# **2. 행렬 연산**

### **2-1. Matrix**
* 행(row) + 열(column)
* 데이터분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음

### **2-2. 덧셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

In [71]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [72]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [73]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[4, 5],
              [2, 3]])

In [74]:
# a + b : ValueError

### **2-3. 뺄셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산

In [75]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [76]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

### **2-4. 곱셈 연산**
* shape가 같아야 함
* 같은 position끼리 연산 

In [77]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [78]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

### **2-5. dot product**
* 맞닿는 shape가 같아야 함

In [80]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])
b = np.array([[1, 2],
             [3, 4],
             [5, 6]])

In [81]:
a.shape, b.shape

((3, 3), (3, 2))

In [83]:
np.dot(a, b) # (앞 행 * 뒤 열)들의 합

array([[22, 28],
       [22, 28],
       [31, 40]])

In [84]:
# (1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
# (1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6)
# (2*1 + 3*3 + 4*5), (2*2 + 3*4 + 4*6)

### **2-6. arange**
* 순차적인 값을 생성할 때 사용

In [85]:
arr = np.arange(1, 11)

In [86]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr = np.arange(start=1, stop=11) # 친절한 표시법

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr = np.arange(start=1, stop=11, step=2) # 간격 설정 가능

In [90]:
arr

array([1, 3, 5, 7, 9])

In [91]:
arr = range(1, 11) # 파이썬 표준 함수와 비교

In [92]:
arr

range(1, 11)

In [93]:
for i in arr: # 객체를 만들어도 되고
  print(i)

1
2
3
4
5
6
7
8
9
10


In [94]:
for i in range(1, 11): # 즉석에서 생성해도 됨
  print(i)

1
2
3
4
5
6
7
8
9
10


In [95]:
arr = np.arange(1, 11) # 객체를 만들어도 되고
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [96]:
for i in np.arange(1, 11): # 즉석에서 생성해도 됨
  print(i)

1
2
3
4
5
6
7
8
9
10


### **2-7. 정렬(sort)**

In [97]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [98]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [99]:
np.sort(arr) # 기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [100]:
np.sort(arr)[::-1] # 내림차순

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [101]:
arr # 파이썬 기본 정렬과 달리 값이 유지되지 않기 때뮨에 변수에 저장해야 함

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [102]:
result = np.sort(arr)

In [103]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [104]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [105]:
arr2d = np.array([[11, 10, 12, 9],
                 [3, 1, 4, 2],
                 [5, 6, 7, 8]])

In [107]:
arr2d.shape

(3, 4)

In [110]:
# 행정렬 : 각 행의 맨 앞 숫자를 기준으로 행 단위로 정렬된다
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [111]:
# 열정렬 : 행 별로 그 안의 열을 비교해 정렬된다
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [113]:
# 마지막 방향 (여기서는 2차원이므로 열정렬)
np.sort(arr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### **2-8. 숫자의 단일 연산**

In [115]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[3, 3, 3],
             [3, 3, 3]])

In [116]:
a + b

array([[4, 5, 6],
       [7, 8, 9]])

In [117]:
a + 3

array([[4, 5, 6],
       [7, 8, 9]])

In [118]:
a - 3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [119]:
a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [120]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])